In [1]:
import tensorflow as tf
tf.set_random_seed(777)

In [2]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [3]:
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [4]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])

In [6]:
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [7]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [8]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [11]:
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [13]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 5.480859 [[ 0.8590572  -0.41383198 -0.5313329 ]
 [-0.76396304 -1.1294101  -0.68536496]
 [-0.07515816  0.06262772 -0.27560872]]
1 3.0121493 [[ 0.78829944 -0.37962323 -0.49478394]
 [-1.0237976  -0.965643   -0.5892976 ]
 [-0.3332764   0.23692864 -0.19179142]]
2 1.7802252 [[ 0.77560353 -0.3955306  -0.46618062]
 [-0.989632   -1.0523365  -0.53676975]
 [-0.29284707  0.15217291 -0.14746502]]
3 1.7091346 [[ 0.74808794 -0.3859926  -0.44820306]
 [-1.0248439  -1.0051568  -0.54873747]
 [-0.32594573  0.20124437 -0.16343783]]
4 1.677143 [[ 0.7330709  -0.39191812 -0.42726052]
 [-1.0013484  -1.0362599  -0.5411299 ]
 [-0.29794338  0.17032814 -0.16052395]]
5 1.6556642 [[ 0.7109699  -0.38797742 -0.40910026]
 [-1.0115142  -1.0166013  -0.55062264]
 [-0.30519563  0.19089557 -0.1738391 ]]
6 1.6374887 [[ 0.69337714 -0.39055508 -0.38892978]
 [-1.0012417  -1.0302997  -0.54719687]
 [-0.29094997  0.17765608 -0.17484525]]
7 1.6208963 [[ 0.67298144 -0.38893232 -0.37015685]
 [-1.004672   -1.0220605  -0.5520056 ]
 [