# Multi-varaible linear regression

In [3]:
import tensorflow as tf
tf.set_random_seed(777)

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [4]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [8]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [9]:
hypothesis = tf.matmul(X,W) + b

In [10]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [12]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [17]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost", cost_val,"\nPredicition:\n",hy_val)

0 Cost 0.9676054 
Predicition:
 [[151.22629]
 [184.96504]
 [180.57538]
 [194.92503]
 [143.65878]]
10 Cost 0.96504176 
Predicition:
 [[151.22871]
 [184.96332]
 [180.57608]
 [194.92583]
 [143.65628]]
20 Cost 0.96248645 
Predicition:
 [[151.23116]
 [184.96164]
 [180.57678]
 [194.92665]
 [143.65381]]
30 Cost 0.959949 
Predicition:
 [[151.23358]
 [184.95995]
 [180.5775 ]
 [194.92744]
 [143.65132]]
40 Cost 0.9574238 
Predicition:
 [[151.23598]
 [184.95825]
 [180.57819]
 [194.92825]
 [143.64885]]
50 Cost 0.9549038 
Predicition:
 [[151.23839]
 [184.95656]
 [180.57887]
 [194.92908]
 [143.6464 ]]
60 Cost 0.9524145 
Predicition:
 [[151.24078]
 [184.95488]
 [180.57959]
 [194.92987]
 [143.64394]]
70 Cost 0.9499218 
Predicition:
 [[151.24321]
 [184.95323]
 [180.58029]
 [194.93068]
 [143.6415 ]]
80 Cost 0.9474441 
Predicition:
 [[151.24557]
 [184.95154]
 [180.58096]
 [194.93147]
 [143.63904]]
90 Cost 0.9449976 
Predicition:
 [[151.24796]
 [184.94989]
 [180.58167]
 [194.93228]
 [143.63663]]
100 Cost 0

1090 Cost 0.75141805 
Predicition:
 [[151.45468]
 [184.80518]
 [180.64116]
 [195.00513]
 [143.42159]]
1100 Cost 0.7499234 
Predicition:
 [[151.45647]
 [184.80391]
 [180.64165]
 [195.00577]
 [143.4197 ]]
1110 Cost 0.7484404 
Predicition:
 [[151.45825]
 [184.80267]
 [180.64217]
 [195.00642]
 [143.41782]]
1120 Cost 0.7469491 
Predicition:
 [[151.46002]
 [184.80142]
 [180.64265]
 [195.00708]
 [143.41592]]
1130 Cost 0.745479 
Predicition:
 [[151.46179]
 [184.80019]
 [180.64317]
 [195.00775]
 [143.41406]]
1140 Cost 0.7440127 
Predicition:
 [[151.46355]
 [184.79893]
 [180.64366]
 [195.00839]
 [143.41219]]
1150 Cost 0.7425453 
Predicition:
 [[151.4653 ]
 [184.79771]
 [180.64417]
 [195.00905]
 [143.41031]]
1160 Cost 0.7410873 
Predicition:
 [[151.46706]
 [184.79648]
 [180.64465]
 [195.0097 ]
 [143.40845]]
1170 Cost 0.7396413 
Predicition:
 [[151.4688 ]
 [184.79526]
 [180.64516]
 [195.01038]
 [143.4066 ]]
1180 Cost 0.7382023 
Predicition:
 [[151.47054]
 [184.79404]
 [180.64566]
 [195.01102]
 [14