In [1]:
import tensorflow as tf
tf.set_random_seed(777)

In [2]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [3]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])

In [4]:
nb_classes = 3

In [6]:
W = tf.Variable(tf.random_normal([4,nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [7]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

In [8]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [13]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)
        
    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 10.362173
200 0.6924536
400 0.57406926
600 0.47874734
800 0.38746056
1000 0.2970224
1200 0.23565182
1400 0.21370767
1600 0.19535741
1800 0.17978686
2000 0.16642171
--------------
[[8.9705149e-03 9.9102038e-01 9.1276215e-06]] [1]
--------------
[[0.8305057  0.1581759  0.01131838]] [0]
--------------
[[2.5463207e-08 4.0876862e-04 9.9959117e-01]] [2]
--------------
[[8.9705139e-03 9.9102038e-01 9.1276215e-06]
 [8.3050573e-01 1.5817590e-01 1.1318383e-02]
 [2.5463207e-08 4.0876865e-04 9.9959117e-01]] [1 0 2]
